# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:11802/test
    username: root
    password: root
  flyway:
    enabled: false

server:
  port: 8088
# 포트 문제로 안될시에 여기 포트 번호 바꿔서 하시면 됩니다.

logging:
  config: classpath:logback-local.xml